"""Add position to collection

Revision ID: 20c1cfce7185
Revises: 
Create Date: 2025-12-16 16:33:40.783165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20c1cfce7185'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'position',
                sa.Integer(),
                nullable=False,
                server_default='0'
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.drop_column('position')

    # ### end Alembic commands ###
